version: '3.1'
include:
  - docker-compose-aux.yml
services:
  server:
    restart: always
    ports:
      - 1234:1234
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 1234
      SERVER_DB_POSTGRES: postgresql://postgres:postgres@db/db
    build:
      context: .
